'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'pt' | 'en';

const TRANSLATIONS = {
  pt: {
    nav: {
      overview: 'Overview',
      machines: 'Máquinas',
      workers:  'Trabalhadores',
      forecast: 'Previsão IA',
      alerts:   'Alertas',
    },
    header: {
      '/':              ['Dashboard Overview',   'Monitorização preditiva · Orion Context Broker'],
      '/maquinas':      ['Gestão de Máquinas',   'Agentes IoT registados no Orion Context Broker'],
      '/trabalhadores': ['Trabalhadores',         'Gestão de contas e acessos'],
      '/previsao':      ['Previsão com IA',       'Modelo LSTM · consumo e ocorrências nas próximas horas'],
      '/alertas':       ['Centro de Alertas',     'Ocorrências críticas, em manutenção e resolvidas'],
    } as Record<string, [string, string]>,
    addMachine:   'Adicionar máquina',
    newWorker:    'Novo trabalhador',
    broker:       'Broker FiWare',
    brokerSub:    'Orion Context Broker online',
    activeAgents: 'agentes ativos',
    monitoring:   'MONITORIZAÇÃO',
    notifications: {
      title:      'Notificações',
      none:       'Sem alertas ativos',
      noneDesc:   'Todas as máquinas operacionais',
      allOk:      'Todas as máquinas operacionais',
      refreshes:  'atualiza em 15s',
      critical:   (n: number) => `${n} crítico${n !== 1 ? 's' : ''}`,
      warning:    (n: number) => `${n} aviso${n !== 1 ? 's' : ''}`,
      active:     (n: number) => `${n} alerta${n !== 1 ? 's' : ''} ativo${n !== 1 ? 's' : ''}`,
      labelError: 'Crítico',
      labelWarn:  'Aviso',
    },
    dash: {
      energyToday:        'Energia consumida (hoje)',
      factoryStatus:      'Estado da fábrica',
      latestAlert:        'Alerta mais recente',
      nextHourForecast:   'Previsão próxima hora',
      noAlerts:           'Sem alertas activos',
      allOperational:     'Todas as máquinas operacionais',
      outOfService:       'fora de serviço',
      operational:        'operacionais',
      avgLabel:           'média',
      machinesLabel:      'máquinas',
      loading:            'A carregar…',
      soonBadge:          'em breve',
      lstmNotAvail:       'Endpoint LSTM ainda não disponível',
      energyMachines:     (n: number, avg: string) => `${n} máquinas · média ${avg} kWh`,
      opRisk:             'Risco operacional',
      opRiskSub:          'Resumo do risco previsto por máquina.',
      latestEvents:       'Últimas ocorrências',
      latestEventsSub:    'Eventos recentes que precisam de atenção ou acompanhamento.',
      critical:           'Crítico',
    },
    mach: {
      title:          'Gestão de Máquinas',
      description:    'Inventário completo dos Agentes IoT. Cada máquina publica telemetria em NGSI-v2 para o Orion Context Broker.',
      registeredAgents: 'Agentes registados',
      withIncident:   'com incidência',
      aggregated:     'Consumo agregado',
      aggregatedSub:  'Soma em tempo real de todas as máquinas',
      avgUptime:      'Uptime médio',
      uptimeSub:      'Histórico de uptime ainda não disponível',
      uptimeSubAvailable: '% de leituras em estado "running" nas últimas 24h',
      statusTitle:    'Estado das máquinas · tempo real',
      statusSub:      'Telemetria enviada pelos Agentes IoT para o Orion Context Broker.',
      yarnTitle:      'Matéria-prima restante por máquina',
      yarnSub:        'Fio (Fiação/Tecelagem) ou corante (Tingimento), conforme o tipo de máquina.',
      energyTitle:    'Energia consumida por máquina',
      energySub:      'Consumo por agente IoT nas últimas leituras agregadas.',
      envTitle:       'Condições ambientais por linha',
      envSub:         'Leituras agregadas dos sensores de temperatura e humidade.',
      all:            'Todos',
      colId:          'ID',
      colMachine:     'Máquina',
      colStatus:      'Status',
      colYarn:        'Matéria-prima restante',
      colConsumption: 'Consumo',
      colLastError:   'Último erro',
      colUpdated:     'Atualizado',
      lineNorthTemp:  'Fiação · Tecelagem · temperatura',
      lineSouthTemp:  'Tingimento · temperatura',
      avgHumidity:    'Humidade média',
      colControl:     'Controlo',
      startBtn:       'Ligar',
      stopBtn:        'Parar',
      stopped:        'Parado',
      waterTitle:     'Consumo de água e químicos · Tingimento',
      waterSub:       'Leituras dos sensores de água e nível de corante por máquina.',
      airTitle:       'Consumo de ar comprimido · Fiação & Tecelagem',
      airSub:         'Leituras do débito de ar comprimido por máquina.',
      water:          'Água',
      chemical:       'Nível de corante',
      compressedAir:  'Ar comprimido',
    },
    fore: {
      title:          'Previsão com IA · LSTM',
      description:    'Modelo recorrente que usa 12h de telemetria agregada (blocos de 5 min) para prever o consumo energético da próxima hora, e um classificador de probabilidade de falha nos próximos 15 minutos.',
      mae:            'MAE · consumo',
      maeSub:         'Erro médio absoluto no conjunto de teste (20% mais recente, split 80/20)',
      accuracy:       'Acurácia · falhas',
      accuracySub:    'Classificação binária · janelas de 15 minutos',
      lastRetrain:    'Última retraining',
      retrainSub:     'Pipeline automático a cada 5 minutos',
      failureRisk:    'Probabilidade de falha por máquina',
      failureRiskSub: 'Classificação preditiva do risco operacional nos próximos 15 minutos.',
      panelTitle:     'Consumo energético · histórico + previsão',
      panelSub:       'Últimos 60 minutos de telemetria e projeção da próxima hora (12 blocos de 5 min) pelo modelo LSTM.',
      histLabel:      'Histórico',
      foreLabel:      'Previsão IA',
      currentConsumption: 'Consumo atual',
      avgForecast:    'Previsão média (1h)',
      expectedVar:    'Variação esperada',
      now:            'agora',
      yarnRemaining:  'Fio restante',
      chemicalRemaining: 'Corante restante',
      urgentRefill:   'Reposição urgente recomendada.',
      withinRange:    'Nível dentro do intervalo operacional.',
      failureProb:    'Probabilidade nos próximos 15min',
      loadingData:    'A carregar dados…',
      modelOutput:    'Saída do modelo',
      errorRange:     'Intervalo de erro da previsão',
    },
    alrt: {
      title:          'Centro de Alertas',
      description:    'Regras definidas sobre atributos NGSI acionam notificações quando os limites são excedidos.',
      open:           'Alertas abertos',
      openSub:        'Requerem ação imediata da equipa de manutenção',
      inReview:       'Em análise',
      inReviewSub:    'Atribuídos a técnicos no terreno',
      resolved:       'Resolvidos (24h)',
      resolvedSub:    'Tempo médio de resolução · 14 min',
      severityTitle:  'Alertas por severidade ao longo do tempo',
      severitySub:    'Evolução das ocorrências críticas, avisos e informativas por intervalo.',
      errorsTitle:    'Códigos de erro por máquina',
      errorsSub:      'Eventos NGSI agregados por intervalo e por máquina.',
      histTitle:      'Histórico de alertas',
      histSub:        'Eventos gerados pelas regras de subscrição do Orion Context Broker.',
      colId:          'ID',
      colMachine:     'Máquina',
      colOccurrence:  'Ocorrência',
      colSeverity:    'Severidade',
      colStatus:      'Status',
      colFired:       'Disparado',
      colAction:      'Ação',
      critical:       'Crítico',
      warning:        'Aviso',
      info:           'Info',
      statusOpen:     'Aberto',
      statusInReview: 'Em análise',
      statusResolved: 'Resolvido',
      errorCode:      'código',
      resolve:        'Resolver',
    },
    workers: {
      title:          'Trabalhadores',
      countSingle:    'utilizador registado',
      countPlural:    'utilizadores registados',
      newBtn:         'Novo trabalhador',
      loadingMsg:     'A carregar…',
      emptyTitle:     'Ainda não há trabalhadores registados.',
      emptyAction:    'Clique em',
      emptyActionBtn: 'Novo trabalhador',
      emptyActionEnd: 'para adicionar.',
      modalTitle:     'Novo trabalhador',
      modalSub:       'Preenche os dados para criar a conta.',
      labelName:      'Nome completo',
      placeholderName: 'ex: João Silva',
      labelUsername:  'Nome de utilizador',
      placeholderUsername: 'ex: joao.silva',
      labelDept:      'Departamento',
      noDept:         'Sem departamento',
      labelPassword:  'Palavra-passe',
      placeholderPwd: 'mínimo 6 caracteres',
      labelConfirm:   'Confirmar',
      placeholderConfirm: 'repetir palavra-passe',
      btnCancel:      'Cancelar',
      btnCreate:      'Criar trabalhador',
      removeTitle:    'Remover trabalhador',
      removeMsg:      (username: string) => `Tens a certeza que queres remover @${username}? Esta ação não pode ser desfeita.`,
      btnRemove:      'Remover',
    },
    modal: {
      title:        'Provisionar novo Agente IoT',
      description:  'Define os parâmetros base. A máquina será registada no Orion Context Broker e começará a enviar telemetria automaticamente. O ID é gerado automaticamente.',
      labelName:    'Nome',
      labelType:    'Tipo de máquina',
      paramsLegend: 'Parâmetros de simulação',
      limitBase:    'Consumo base',
      baseThread:   'Fio na bobine (cheia)',
      baseWater:    'Consumo de água base',
      baseChemical: 'Corante (capacidade)',
      baseAir:      'Ar comprimido base',
      btnCancel:    'Cancelar',
      btnProvision: 'Provisionar agente',
      submitting:   'A criar…',
      errorGeneric: 'Não foi possível criar a máquina.',
      successMsg:   'Máquina criada com sucesso.',
    },
  },

  en: {
    nav: {
      overview: 'Overview',
      machines: 'Machines',
      workers:  'Workers',
      forecast: 'AI Forecast',
      alerts:   'Alerts',
    },
    header: {
      '/':              ['Dashboard Overview',   'Predictive monitoring · Orion Context Broker'],
      '/maquinas':      ['Machine Management',   'IoT agents registered in Orion Context Broker'],
      '/trabalhadores': ['Workers',              'Account and access management'],
      '/previsao':      ['AI Forecast',          'LSTM model · energy forecast for the next hours'],
      '/alertas':       ['Alert Center',         'Critical, maintenance and resolved occurrences'],
    } as Record<string, [string, string]>,
    addMachine:   'Add machine',
    newWorker:    'New worker',
    broker:       'FiWare Broker',
    brokerSub:    'Orion Context Broker online',
    activeAgents: 'active agents',
    monitoring:   'MONITORING',
    notifications: {
      title:      'Notifications',
      none:       'No active alerts',
      noneDesc:   'All machines operational',
      allOk:      'All machines operational',
      refreshes:  'refreshes in 15s',
      critical:   (n: number) => `${n} critical`,
      warning:    (n: number) => `${n} warning${n !== 1 ? 's' : ''}`,
      active:     (n: number) => `${n} active alert${n !== 1 ? 's' : ''}`,
      labelError: 'Critical',
      labelWarn:  'Warning',
    },
    dash: {
      energyToday:        'Energy consumed (today)',
      factoryStatus:      'Factory status',
      latestAlert:        'Latest alert',
      nextHourForecast:   'Next hour forecast',
      noAlerts:           'No active alerts',
      allOperational:     'All machines operational',
      outOfService:       'out of service',
      operational:        'operational',
      avgLabel:           'average',
      machinesLabel:      'machines',
      loading:            'Loading…',
      soonBadge:          'soon',
      lstmNotAvail:       'LSTM endpoint not yet available',
      energyMachines:     (n: number, avg: string) => `${n} machines · average ${avg} kWh`,
      opRisk:             'Operational risk',
      opRiskSub:          'Predicted risk summary per machine.',
      latestEvents:       'Latest occurrences',
      latestEventsSub:    'Recent events that require attention or follow-up.',
      critical:           'Critical',
    },
    mach: {
      title:          'Machine Management',
      description:    'Complete IoT Agent inventory. Each machine publishes telemetry in NGSI-v2 to the Orion Context Broker.',
      registeredAgents: 'Registered agents',
      withIncident:   'with incident',
      aggregated:     'Aggregated consumption',
      aggregatedSub:  'Real-time sum of all machines',
      avgUptime:      'Average uptime',
      uptimeSub:      'Uptime history not yet available',
      uptimeSubAvailable: '% of readings in "running" state over the last 24h',
      statusTitle:    'Machine status · real time',
      statusSub:      'Telemetry sent by IoT Agents to the Orion Context Broker.',
      yarnTitle:      'Raw material remaining per machine',
      yarnSub:        'Thread (Spinning/Weaving) or dye (Dyeing), depending on machine type.',
      energyTitle:    'Energy consumed per machine',
      energySub:      'Per IoT agent consumption in the latest aggregated readings.',
      envTitle:       'Environmental conditions by line',
      envSub:         'Aggregated readings from temperature and humidity sensors.',
      all:            'All',
      colId:          'ID',
      colMachine:     'Machine',
      colStatus:      'Status',
      colYarn:        'Raw material remaining',
      colConsumption: 'Consumption',
      colLastError:   'Last error',
      colUpdated:     'Updated',
      lineNorthTemp:  'Spinning · Weaving · temperature',
      lineSouthTemp:  'Dyeing · temperature',
      avgHumidity:    'Average humidity',
      colControl:     'Control',
      startBtn:       'Start',
      stopBtn:        'Stop',
      stopped:        'Stopped',
      waterTitle:     'Water & chemical consumption · Dyeing',
      waterSub:       'Water and dye level sensor readings per machine.',
      airTitle:       'Compressed air consumption · Spinning & Weaving',
      airSub:         'Compressed air flow readings per machine.',
      water:          'Water',
      chemical:       'Dye level',
      compressedAir:  'Compressed air',
    },
    fore: {
      title:          'AI Forecast · LSTM',
      description:    'Recurrent model that uses 12h of aggregated telemetry (5-min blocks) to forecast next-hour energy consumption, plus a failure-probability classifier for the next 15 minutes.',
      mae:            'MAE · consumption',
      maeSub:         'Mean absolute error on the test set (most recent 20%, 80/20 split)',
      accuracy:       'Accuracy · failures',
      accuracySub:    'Binary classification · 15 minute windows',
      lastRetrain:    'Last retraining',
      retrainSub:     'Automatic pipeline every 5 minutes',
      failureRisk:    'Failure probability per machine',
      failureRiskSub: 'Predictive classification of operational risk in the next 15 minutes.',
      panelTitle:     'Energy consumption · history + forecast',
      panelSub:       'Last 60 minutes of telemetry and next-hour projection (12 blocks of 5 min) by the LSTM model.',
      histLabel:      'History',
      foreLabel:      'AI Forecast',
      currentConsumption: 'Current consumption',
      avgForecast:    'Average forecast (1h)',
      expectedVar:    'Expected variation',
      now:            'now',
      yarnRemaining:  'Thread remaining',
      chemicalRemaining: 'Dye remaining',
      urgentRefill:   'Urgent refill recommended.',
      withinRange:    'Level within operational range.',
      failureProb:    'Failure probability next 15min',
      loadingData:    'Loading data…',
      modelOutput:    'Model output',
      errorRange:     'Forecast error range',
    },
    alrt: {
      title:          'Alert Center',
      description:    'Rules defined on NGSI attributes trigger notifications when thresholds are exceeded.',
      open:           'Open alerts',
      openSub:        'Require immediate action from the maintenance team',
      inReview:       'In review',
      inReviewSub:    'Assigned to field technicians',
      resolved:       'Resolved (24h)',
      resolvedSub:    'Average resolution time · 14 min',
      severityTitle:  'Alerts by severity over time',
      severitySub:    'Evolution of critical, warning and informational occurrences by interval.',
      errorsTitle:    'Error codes per machine',
      errorsSub:      'NGSI events aggregated by interval and machine.',
      histTitle:      'Alert history',
      histSub:        'Events generated by Orion Context Broker subscription rules.',
      colId:          'ID',
      colMachine:     'Machine',
      colOccurrence:  'Occurrence',
      colSeverity:    'Severity',
      colStatus:      'Status',
      colFired:       'Triggered',
      colAction:      'Action',
      critical:       'Critical',
      warning:        'Warning',
      info:           'Info',
      statusOpen:     'Open',
      statusInReview: 'In review',
      statusResolved: 'Resolved',
      errorCode:      'code',
      resolve:        'Resolve',
    },
    workers: {
      title:          'Workers',
      countSingle:    'registered user',
      countPlural:    'registered users',
      newBtn:         'New worker',
      loadingMsg:     'Loading…',
      emptyTitle:     'No workers registered yet.',
      emptyAction:    'Click',
      emptyActionBtn: 'New worker',
      emptyActionEnd: 'to add one.',
      modalTitle:     'New worker',
      modalSub:       'Fill in the details to create the account.',
      labelName:      'Full name',
      placeholderName: 'e.g. John Smith',
      labelUsername:  'Username',
      placeholderUsername: 'e.g. john.smith',
      labelDept:      'Department',
      noDept:         'No department',
      labelPassword:  'Password',
      placeholderPwd: 'minimum 6 characters',
      labelConfirm:   'Confirm',
      placeholderConfirm: 'repeat password',
      btnCancel:      'Cancel',
      btnCreate:      'Create worker',
      removeTitle:    'Remove worker',
      removeMsg:      (username: string) => `Are you sure you want to remove @${username}? This action cannot be undone.`,
      btnRemove:      'Remove',
    },
    modal: {
      title:        'Provision new IoT Agent',
      description:  'Set the base parameters. The machine will be registered in the Orion Context Broker and will start sending telemetry automatically. The ID is generated automatically.',
      labelName:    'Name',
      labelType:    'Machine type',
      paramsLegend: 'Simulation parameters',
      limitBase:    'Base consumption',
      baseThread:   'Thread on bobbin (full)',
      baseWater:    'Base water consumption',
      baseChemical: 'Dye (capacity)',
      baseAir:      'Base compressed air',
      btnCancel:    'Cancel',
      btnProvision: 'Provision agent',
      submitting:   'Creating…',
      errorGeneric: 'Could not create the machine.',
      successMsg:   'Machine created successfully.',
    },
  },
} as const;

export type Translations = typeof TRANSLATIONS.pt;

const LangContext = createContext<{ lang: Lang; toggle: () => void; t: Translations }>({
  lang: 'pt',
  toggle: () => {},
  t: TRANSLATIONS.pt,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('pt');

  function toggle() {
    setLang(l => (l === 'pt' ? 'en' : 'pt'));
  }

  return (
    <LangContext.Provider value={{ lang, toggle, t: TRANSLATIONS[lang] as Translations }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
