apiVersion: 1

datasources:
  - name: CrateDB
    type: postgres
    url: crate:5432
    database: doc
    user: crate
    secureJsonData:
      password: ""
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
    isDefault: true
    editable: true
